import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:flutter_app/shared/services/supabase_service.dart';
import 'package:flutter_app/features/customer_tracking/domain/customer_tracking_repository.dart';
import 'package:flutter_app/features/customer_tracking/domain/customer_event.dart';
import 'package:flutter_app/features/customer_tracking/data/customer_event_model.dart';

class CustomerTrackingRepositoryImpl implements CustomerTrackingRepository {
  final SupabaseClient _supabaseClient;

  CustomerTrackingRepositoryImpl({SupabaseClient? supabaseClient})
    : _supabaseClient = supabaseClient ?? SupabaseService.client;

  @override
  Future<List<CustomerEvent>> getCustomerEvents() async {
    try {
      final userId = _supabaseClient.auth.currentUser?.id;
      if (userId == null) {
        print('User is not authenticated.');
        return [];
      }

      final response = await _supabaseClient
          .from('reminders')
          .select()
          .eq('user_id', userId)
          .order('event_date', ascending: true);

      // ignore: avoid_print
      print('Supabase customer events response: $response');

      final events = (response as List)
          .map((data) => CustomerEventModel.fromJson(data))
          .toList();
      return events;
    } catch (e, st) {
      // TODO: Add proper error handling
      print('Error fetching customer events: $e');
      print('Stacktrace: $st');
      rethrow;
    }
  }

  @override
  Future<void> addCustomerEvent(CustomerEvent event) async {
    try {
      final userId = _supabaseClient.auth.currentUser?.id;
      if (userId == null) {
        throw Exception('User not authenticated');
      }

      final model = CustomerEventModel(
        id: event.id, // ID might be generated by DB, but model requires it
        userId: userId,
        clientName: event.clientName,
        clientPhone: event.clientPhone,
        eventType: event.eventType,
        eventDate: event.eventDate,
        notes: event.notes,
        lastPurchaseReference: event.lastPurchaseReference,
        createdAt: DateTime.now(), // Handled by DB default
        updatedAt: DateTime.now(), // Handled by DB default/trigger
        status: event.status,
      );

      // Insert and select the created row to get DB feedback
      final response = await _supabaseClient
          .from('reminders')
          .insert(model.toJsonForInsert())
          .select();

      print('Event added successfully: $response');
    } catch (e, st) {
      print('Error adding customer event: $e');
      print('Stacktrace: $st');
      rethrow;
    }
  }

  @override
  Future<void> updateCustomerEvent(CustomerEvent event) async {
    try {
      final userId = _supabaseClient.auth.currentUser?.id;
      if (userId == null) {
        throw Exception('User not authenticated');
      }

      final model = CustomerEventModel(
        id: event.id,
        userId: userId, // ensure we use authenticated user's id
        clientName: event.clientName,
        clientPhone: event.clientPhone,
        eventType: event.eventType,
        eventDate: event.eventDate,
        notes: event.notes,
        lastPurchaseReference: event.lastPurchaseReference,
        createdAt: event.createdAt,
        updatedAt: event.updatedAt,
        status: event.status,
      );

      final response = await _supabaseClient
          .from('reminders')
          .update(model.toJsonForUpdate())
          .eq('id', event.id)
          .eq('user_id', userId)
          .select();

      print('Event updated successfully: $response');
    } catch (e, st) {
      print('Error updating customer event: $e');
      print('Stacktrace: $st');
      rethrow;
    }
  }

  @override
  Future<void> deleteCustomerEvent(String eventId) async {
    try {
      final userId = _supabaseClient.auth.currentUser?.id;
      if (userId == null) {
        throw Exception('User not authenticated');
      }

      await _supabaseClient
          .from('reminders')
          .delete()
          .eq('id', eventId)
          .eq('user_id', userId);

      print('Event deleted successfully');
    } catch (e, st) {
      print('Error deleting customer event: $e');
      print('Stacktrace: $st');
      rethrow;
    }
  }
}
